=== kids-first/kf-dev-single-cell-rna/nf/SWANS_INTERACTIVE/nextflow_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "https://raw.githubusercontent.com/nf/SWANS_INTERACTIVE/master/nextflow_schema.json",
    "title": "nf/SWANS_INTERACTIVE pipeline parameters",
    "description": "",
    "type": "object",
    "definitions": {
        "input_output_options": {
            "title": "Input/output options",
            "type": "object",
            "fa_icon": "fas fa-terminal",
            "description": "Define where the pipeline should find input data and save output data.",
            "properties": {
                "outdir": {
                    "type": "string",
                    "description": "Path to the output directory where the results will be saved.",
                    "default": "./results",
                    "fa_icon": "fas fa-folder-open"
                }
            }
        },
        "reference_genome_options": {
            "title": "Reference genome options",
            "type": "object",
            "fa_icon": "fas fa-dna",
            "description": "Reference genome related files and options required for the workflow.",
            "properties": {}
        },
        "institutional_config_options": {
            "title": "Institutional config options",
            "type": "object",
            "fa_icon": "fas fa-university",
            "description": "Parameters used to describe centralised config profiles. These should not be edited.",
            "help_text": "The centralised nf-core configuration profiles use a handful of pipeline parameters to describe themselves. This information is then printed to the Nextflow log when you run a pipeline. You should not need to change these values when you run a pipeline.",
            "properties": {}
        },
        "max_job_request_options": {
            "title": "Max job request options",
            "type": "object",
            "fa_icon": "fab fa-acquisitions-incorporated",
            "description": "Set the top limit for requested resources for any single job.",
            "help_text": "If you are running on a smaller system, a pipeline step requesting more resources than are available may cause the Nextflow to stop the run with an error. These options allow you to cap the maximum resources requested by any single job so that the pipeline will run on your system.\n\nNote that you can not _increase_ the resources requested by any job using these options. For that you will need your own configuration file. See [the nf-core website](https://nf-co.re/usage/configuration) for details.",
            "properties": {
                "max_cpus": {
                    "type": "integer",
                    "description": "Maximum number of CPUs that can be requested for any single job.",
                    "default": 16,
                    "fa_icon": "fas fa-microchip",
                    "hidden": true,
                    "help_text": "Use to set an upper-limit for the CPU requirement for each process. Should be an integer e.g. `--max_cpus 1`"
                },
                "max_memory": {
                    "type": "string",
                    "description": "Maximum amount of memory that can be requested for any single job.",
                    "default": "128.GB",
                    "fa_icon": "fas fa-memory",
                    "pattern": "^\\d+(\\.\\d+)?\\.?\\s*(K|M|G|T)?B$",
                    "hidden": true,
                    "help_text": "Use to set an upper-limit for the memory requirement for each process. Should be a string in the format integer-unit e.g. `--max_memory '8.GB'`"
                },
                "max_time": {
                    "type": "string",
                    "description": "Maximum amount of time that can be requested for any single job.",
                    "default": "240.h",
                    "fa_icon": "far fa-clock",
                    "pattern": "^(\\d+\\.?\\s*(s|m|h|day)\\s*)+$",
                    "hidden": true,
                    "help_text": "Use to set an upper-limit for the time requirement for each process. Should be a string in the format integer-unit e.g. `--max_time '2.h'`"
                }
            }
        },
        "generic_options": {
            "title": "Generic options",
            "type": "object",
            "fa_icon": "fas fa-file-import",
            "description": "Less common options for the pipeline, typically set in a config file.",
            "help_text": "These options are common to all nf-core pipelines and allow you to customise some of the core preferences for how the pipeline runs.\n\nTypically these options would be set in a Nextflow config file loaded for all pipeline runs, such as `~/.nextflow/config`.",
            "properties": {}
        }
    },
    "allOf": [
        {
            "$ref": "#/definitions/input_output_options"
        },
        {
            "$ref": "#/definitions/reference_genome_options"
        },
        {
            "$ref": "#/definitions/institutional_config_options"
        },
        {
            "$ref": "#/definitions/max_job_request_options"
        },
        {
            "$ref": "#/definitions/generic_options"
        }
    ],
    "properties": {
        "r_lib_path": {
            "type": "string",
            "default": "/usr/local/lib/R/site-library/"
        },
        "project": {
            "type": "string"
        },
        "initial_seurat_object": {
            "type": "string",
            "format": "file-path",
            "description": "qs file output from SWANS Data Cleanup and QC"
        },
        "organism": {
            "type": "string",
            "default": "human",
            "enum": ["human", "mouse"]
        },
        "mito_cutoff": {
            "type": "integer",
            "default": 15,
            "description": "mitochondrial cutoff percent as int. Set to 100 to filter nothing"
        },
        "ribo_cutoff": {
            "type": "integer",
            "default": 100,
            "description": "ribosomal cutoff percent as int. Set to 100 to filter nothing"
        },
        "int_components": {
            "type": "integer",
            "default": 30,
           "description": "number of pcs to use in seurat"
        },
        "aso_processes": {
            "type": "integer",
            "default": 4,
            "description": "Number of processes to use for parallel processing in analyze_seurat_object module"
        },
        "aso_memory": {
            "type": "integer",
            "default": 30000000000
        },
        "run_azimuth": {
            "type": "string",
            "default": "n",
            "enum": ["n", "y"]
        },
        "azimuth_ref": {
            "type": "string",
            "description": "azimuth reference dataset to use for annotation"
        },
        "run_transferdata": {
            "type": "string",
            "default": "n",
            "enum": ["n", "y"]
        },
        "transferdata_ref_file": {
            "type": "string",
            "format": "file-path",
            "description": "path to reference Seurat object for TransferData"
        },
        "transferdata_reduction": {
            "type": "string",
            "description": "which dimensional reduction in the transferdata_ref_file to use for transferdata"
        },
        "transferdata_annocol": {
            "type": "string",
            "description": "which seurat meta.data column to use for transferdata annotation"
        },
        "mito_regression": {
            "type": "string",
            "default": "n",
            "enum": ["n", "y"],
            "description": "should mito percent be regressed"
        },
        "ribo_regression": {
            "type": "string",
            "default": "n",
            "enum": ["n", "y"],
            "description": "should ribo percent be regressed"
        },
        "cc_method": {
            "type": "string",
            "description": "Method for cell cycle scoring: standard or alternative",
            "enum": ["standard", "alternative"]
        },
        "num_var_features": {
            "type": "integer",
            "description": "Number of variable features (genes) to use in normalization",
            "default": 3000
        },
        "resolution_config": {
            "type": "string",
            "description": "resolution value(s) as csv string, i.e. 0.5 or 0.1,0.2,0.3",
            "default": "0.1,0.2,0.3"
        },
        "include_tsne": {
            "type": "string",
            "default": "n",
            "description": "make tsne plots",
            "enum": ["n", "y"]
        },
        "scale_data_features": {
            "type": "string",
            "description": "which features to use for scale data",
            "default": "variable",
            "enum": ["variable", "all"]
        },
        "split_layers_by": {
            "type": "string",
            "default": "Sample",
            "description": "metadata by which to split the object into layers (experiment, sample (recommended))"

        },
        "normalization_config": {
            "type": "string",
            "description": "normalization method for Seurat (standard, sct) as csv string -- choose one or all",
            "default": "standard,sct"
        },
        "integration_config": {
            "type": "string",
            "description": "integration method for seurat (cca, rpca, harmony) as csv -- choose any combination or all options",
            "default": "cca,rpca,harmony"
        },
        "ref_based_integration": {
            "type": "string",
            "default": "n",
            "enum": ["n", "y"]
        },
        "ref_samples": {
            "type": "string",
            "description": "which sample(s) to use as references for ref-based integration? (names from samples.sample_list)"
        },
        "regression_file": {
            "type": "string",
            "format": "file-path",
            "description": "file of additional genes to be regressed"
        },
        "storage": {
            "type": "string",
            "default": "rds",
            "enum": ["rds", "sceo"]
        },
        "conserved_genes": {
            "type": "string",
            "default": "n",
            "description": "run conserved genes (y/n) -- only run with multiple experiments",
            "enum": ["n", "y"]
        },
        "visualization": {
            "type": "string",
            "default": "dot"
        },
        "user_gene_file": {
            "type": "string",
            "format": "file-path",
            "description": "relative path with filename to file containing genes of interest"
        },
        "aws_test_instance": {
            "type": "boolean"
        },
        "sbg_run": {
            "type": "boolean"
        }
    }
}

=== kids-first/kf-dev-single-cell-rna/nf/SWANS_INTERACTIVE/test_inputs/cr_h5_test.json
{
    "project": "HOPE_TEST_H5_CR_MIXED",
    "initial_seurat_object": "/home/ubuntu/volume/SB/projects/d3b-bixu/kf-dev-single-cell-rna/HOPE_TEST_H5_CR_MIXED_initial_seurat_object.qs",
    "include_tsne" : "y",
    "run_azimuth": "y",
    "azimuth_ref": "humancortexref",
    "organism": "human",
    "aws_test_instance": true
}
